//.........................Products list ...................

export const FETCH_PRODUCTLIST_REQUEST = "FETCH_PRODUCTLIST_REQUEST";
export const FETCH_PRODUCTLIST_SUCCEESS = "FETCH_PRODUCTLIST_SUCCESS";
export const FETCH_PRODUCTLIST_FAILURE = "FETCH_PRODUCTLIST_FAILURE";

//........................ Add Products...................

export const FETCH_ADDPRODUCT_REQUEST = "FETCH_ADDPRODUCT_REQUEST";
export const FETCH_ADDPRODUCT_SUCCEESS = "FETCH_ADDPRODUCT_SUCCEESS";
export const FETCH_ADDPRODUCT_FAILURE = "FETCH_ADDPRODUCT_FAILURE";

//.......................Edit Products......................

export const FETCH_EDITPRODUCT_REQUEST = "FETCH_EDITPRODUCT_REQUEST";
export const FETCH_EDITPRODUCT_SUCCEESS = "FETCH_EDITPRODUCT_SUCCEESS";
export const FETCH_EDITPRODUCT_FAILURE = "FETCH_EDITPRODUCT_FAILURE";

//......................Delete Products..............

export const FETCH_DELETEPRODUCT_REQUEST = "FETCH_DELETEPRODUCT_REQUEST";
export const FETCH_DELETEPRODUCT_SUCCEESS = "FETCH_DELETEPRODUCT_SUCCEESS";
export const FETCH_DELETEPRODUCT_FAILURE = "FETCH_DELETEPRODUCT_FAILURE";

//..................Product Get by id..................

export const FETCH_PRODUCTBYID_REQUEST = "FETCH_PRODUCTBYID_REQUEST";
export const FETCH_PRODUCTBYID_SUCCEESS = "FETCH_PRODUCTBYID_SUCCEESS";
export const FETCH_PRODUCTBYID_FAILURE = "FETCH_PRODUCTBYID_FAILURE";
